# TABLE = {'invoice': (
#     "CREATE TABLE `invoice` ("
#     "  invoice_num int NOT NULL ,"
#     "  invoice_date timestamp ,"
#     "  application_id int ,"
#     "  act_id int ,"
#     "  act_date timestamp ,"
#     "   id int ,"
#     "   region varchar(50) ,"
#     "   region_edrpou int ,"
#     "   item_id int ,"
#     "   group_name varchar(50) ,"
#     "   dosage varchar(50) ,"
#     "   release_form varchar(50) ,"
#     "   unit varchar(50) ,"
#     "   trade_name varchar(50) ,"
#     "   multiplicity varchar(50) ,"
#     "   distribution int ,"
#     " PRIMARY KEY (`invoice_num`)"
#     ") ENGINE=InnoDB")}

